/**
 * USER ACTION TYPES
 */
export const GET_USER = 'GET_USER'
export const REMOVE_USER = 'REMOVE_USER'

/**
 * RECEIVER ACTION TYPES
 */
export const ADD_RECEIVER = 'ADD_RECEIVER'
export const GET_ALL_LIST_RECEIVERS = 'GET_ALL_LIST_RECEIVERS'


/**
 * LIST ACTION TYPES
 */
export const GET_CURRENT_LIST_ID = 'GET_CURRENT_LIST_ID'
export const UPDATE_CURRENT_LIST_ID = 'UPDATE_CURRENT_LIST_ID'
export const GET_LISTS_FOR_USER= 'GET_LISTS_FOR_USER'
