/**
 * USER ACTION TYPES
 */
export const GET_USER = 'GET_USER'
export const REMOVE_USER = 'REMOVE_USER'

/**
 * RECEIVER ACTION TYPES
 */
export const ADD_RECEIVER = 'ADD_RECEIVER'
export const GET_ALL_LIST_RECEIVERS = 'GET_ALL_LIST_RECEIVERS'
export const REMOVE_RECEIVER_FROM_LIST = 'REMOVE_RECEIVER_FROM_LIST'
export const REMOVE_ALL_LIST_RECEIVERS = 'REMOVE_ALL_LIST_RECEIVERS'
export const GET_ALL_RECEIVER_GIFTS = 'GET_ALL_RECEIVER_GIFTS'
export const ADD_GIFT_TO_RECEIVER = 'ADD_GIFT_TO_RECEIVER'

/**
 * LIST ACTION TYPES
 */
export const GET_CURRENT_LIST_ID = 'GET_CURRENT_LIST_ID'
export const UPDATE_CURRENT_LIST_ID = 'UPDATE_CURRENT_LIST_ID'
export const UPDATE_PREVIOUS_LIST_ID = 'UPDATE_PREVIOUS_LIST_ID'
export const GET_LISTS_FOR_USER= 'GET_LISTS_FOR_USER'
export const ADD_NEW_LIST = 'ADD_NEW_LIST'
export const DELETE_LIST = 'DELETE_LIST'
export const GET_ALL_GIFTS_FOR_LIST = 'GET_ALL_GIFTS_FOR_LIST'
